apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraganization-chart
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: myapp:v3
          ports:
            - containerPort: 9091
#          env:
#            - name: DB_HOST
#              value: mysql:3306
#
#            - name: DB_NAME
#              value: shrest
#
#            - name: DB_USERNAME
#              value: root
#
#            - name: DB_PASSWORD
#              value: root
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password


---

apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 9091
      nodePort: 30001
  type: NodePort # type of the service.